### ISSUE TITLE
problem building queries with mariadb 10

### ISSUE THREAD

**Issue by ykorzikowski** [motor-admin/motor-admin#13]
```
SELECT 'Hello there'
```

results in

```
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.* FROM "__query__" LIMIT 100000' at line 3
```

running with server

```
 backend_db:
    restart: always
    image: "mariadb:10"
    environment:
      MYSQL_DATABASE: "backend"
      MYSQL_USER: "backend"
      MYSQL_PASSWORD: "backend"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"
```

I think you are buiding some not compatible query for mariadb in this class. 

https://github.com/motor-admin/motor-admin-rails/blob/515695a75b8042a9548a675aaf46c1eec159d5d0/lib/motor/queries/run_query.rb
