### ISSUE TITLE
Strange pre-filled field in custom form

### ISSUE THREAD

**Issue by jakubjanousek** [motor-admin/motor-admin#61]
We have a custom form with one field defined like
<img width="436" alt="Screenshot 2022-08-11 at 14 00 10" src="https://user-images.githubusercontent.com/4403131/184129118-499abdea-516f-454d-8288-3e07de35e2de.png">
but when I try to fill this form (it's assigned to create action on a collection), the field is pre-filled with one of the options (it shouldn't be)
<img width="722" alt="Screenshot 2022-08-11 at 14 01 21" src="https://user-images.githubusercontent.com/4403131/184129239-8c905aa9-f573-4676-bd97-87a046add9d8.png">
but it is still empty as far as validation is concerned
<img width="718" alt="Screenshot 2022-08-11 at 14 03 41" src="https://user-images.githubusercontent.com/4403131/184129310-fd88bae1-c30b-4f4b-b583-c50f9842c163.png">

Here is the field configuration in the form from YAML
```
    - display_name: Service
      name: serviceId
      field_type: reference
      default_value: ''
      validators:
      - required: true
      reference:
        model_name: service
```
Can you see what is going wrong in here? It is just one field that is acting this weird. Also, once the date is filled in and the form is submitted and reopened, that date starts acting the same (it's pre-filled, but marked as empty by validation)
